INPUTS: input
OUTPUTS: output

DATA:
  TRAIN:
    DATASETS: ['train_0e_33_B',  'grid_0e_33_B', 'pseudo_33']
    #FOLDS: [
    #        ['train_0e_33_B', 'pseudo_33', 'grid_0e_33_B','sclero_33'],
    #        ['train_18_33_B', 'pseudo_33', 'grid_18_33_B','sclero_33'],
    #        ['train_ab_33_B', 'pseudo_33', 'grid_ab_33_B','sclero_33'],
    #        ['train_b2_33_B', 'pseudo_33', 'grid_b2_33_B','sclero_33']]
    GPU_PRELOAD: False
    PRELOAD: False
    CACHE: False
    MULTIPLY: {'rate':1}
  VALID:
    DATASETS: ['val_0e_33_B']
    #FOLDS: [
    #        ['val_0e_33_B' ],
    #        ['val_18_33_B' ],
    #        ['val_ab_33_B' ],
    #        ['val_b2_33_B' ]]
    PRELOAD: False
  SSL:
    DATASETS: []
    PRELOAD: False
  TEST:
    DATASETS: []

TRANSFORMERS:
  TRAIN:
    AUG: 'light_scale'
  VALID:
    AUG: 'val'
  SSL:
    AUG: 'ssl'
  TEST:
    AUG: 'test'
  #CROP: [512,512]
  CROP: [1024,1024]
  RESIZE: [256,256]
  MEAN:
  - 0.6226
  - 0.4284
  - 0.6705
  STD:
  - 0.1246
  - 0.1719
  - 0.0956

TRAIN:
  LRS: [0.00001, 0.0004, 0.000015, 1]
  DOWNSCALE: 3
  NUM_FOLDS: 1
  SELECTIVE_BP: 1.
  HARD_MULT: 1
  EMA: 0.999
  #WEIGHTS: 'input/scores_color_train.pkl'
  INIT_MODEL: 'output/2021_May_08_20_09_59_PAMBUH/models/'
  AMP: True
  GPUS: [0,1,2,3]
  NUM_WORKERS: 4
  
  SAVE_STEP: 1.
  SCALAR_STEP: 1
  TB_STEP: 2
  
  EPOCH_COUNT: 40
  BATCH_SIZE: 8
VALID:
  STEP: 2
  BATCH_SIZE: 8
SSL:
  STEP: 1
  BATCH_SIZE: 64
TEST:
  BATCH_SIZE: 1
  
PARALLEL:
  DDP: True
