INPUTS: input
OUTPUTS: output

DATA:
  TRAIN:
    DATASETS: ['train_0e', 'random_0e',  'backs_cort_0e']
    #DATASETS: ['train_0e_b', 'random_0e_b',  'backs_cort_0e_b']
    # FOLDS: [['train_0e', 'random_0e',  'backs_cort_0e'],
    #         ['train_2a', 'random_2a',  'backs_cort_2a'],
    #         ['train_18', 'random_18',  'backs_cort_18'],
    #         ['train_cc', 'random_cc',  'backs_cort_cc']]
    GPU_PRELOAD: False
    PRELOAD: False
    CACHE: False
    MULTIPLY: {'rate':1}
  VALID:
    DATASETS: ['val_0e']
    #FOLDS: [['val_0e'],['val_2a'],['val_18'],['val_cc']]
    PRELOAD: False
  SSL:
    #DATASETS: ['ssl_test', 'ssl_val']
    DATASETS: []
    PRELOAD: False
  TEST:
    DATASETS: []

TRANSFORMERS:
  TRAIN:
    AUG: 'light_scale'
  VALID:
    AUG: 'val'
  SSL:
    AUG: 'ssl'
  TEST:
    AUG: 'test'
  CROP: [256,256]
  RESIZE: [256,256]
  MEAN:
  - 0.6226
  - 0.4284
  - 0.6705
  STD:
  - 0.1246
  - 0.1719
  - 0.0956

TRAIN:
  LRS: [0.00002, 0.0002, 0.00002, 2]
  DOWNSCALE: 4
  NUM_FOLDS: 1
  SELECTIVE_BP: 1.
  HARD_MULT: 2
  EMA: 0.995
  #WEIGHTS: 'input/scores_color_train.pkl'
  #INIT_MODEL: 'output/2021_Apr_01_09_19_26_PAMBUH/models/'
  AMP: True
  GPUS: [1,3]
  NUM_WORKERS: 8
  
  SAVE_STEP: 1.
  SCALAR_STEP: 1
  TB_STEP: 4
  
  EPOCH_COUNT: 100
  BATCH_SIZE: 64
VALID:
  STEP: 4
  BATCH_SIZE: 32
SSL:
  STEP: 1
  BATCH_SIZE: 64
TEST:
  BATCH_SIZE: 1
  
PARALLEL:
  DDP: True
