INPUTS: input
OUTPUTS: output

DATA:
  TRAIN:
    DATASETS: ['train1024x05']
    GPU_PRELOAD: False
    PRELOAD: True
    CACHE: False
    MULTIPLY: {'rate':5}
  VALID:
    DATASETS: ['val1024x05']
    PRELOAD: False
  TEST:
    DATASETS: []

TRANSFORMERS:
  TRAIN:
    AUG: 'light'
  VALID:
    AUG: 'val'
  TEST:
    AUG: 'test'
  CROP: [256, 256]
  RESIZE: [256, 256]

TRAIN:
  AMP: True
  GPUS: [0,1,2,3]
  NUM_WORKERS: 8
  
  SAVE_STEP: 0.3
  SCALAR_STEP: 1
  TB_STEP: 100
  
  EPOCH_COUNT: 2000
  BATCH_SIZE: 64
VALID:
  STEP: 5
  BATCH_SIZE: 64
TEST:
  BATCH_SIZE: 1
  
PARALLEL:
  DDP: True
