INPUTS: input
OUTPUTS: output

DATA:
  TRAIN:
    DATASETS: ['train2i', 'backs_cort2i', 'backs_medu2i', 'backs_rand2i']
    #DATASETS: ['train2048full', 'backs_cort2i', 'backs_medu2i', 'backs_rand2i']
    #DATASETS: ['train2048x25', 'backs_cort', 'backs_rand']
    GPU_PRELOAD: False
    PRELOAD: False
    CACHE: False
    MULTIPLY: {'rate':2}
  VALID:
      #DATASETS: ['val2048x25']
    DATASETS: ['val2i']
    PRELOAD: False
  SSL:
    #DATASETS: ['ssl_test']
    DATASETS: []
    PRELOAD: False
  TEST:
    DATASETS: []

TRANSFORMERS:
  TRAIN:
    AUG: 'light_scale'
  VALID:
    AUG: 'val'
  SSL:
    AUG: 'ssl'
  TEST:
    AUG: 'test'
  CROP: [256,256]
  RESIZE: [256,256]
  MEAN:
  - 0.6226
  - 0.4284
  - 0.6705
  STD:
  - 0.1246
  - 0.1719
  - 0.0956

TRAIN:
  #LRS: [0.00003, 0.0001, 0.00003, 45]
  LRS: [0.00002, 0.0001, 0.00002, 2]
  DOWNSCALE: 4
  NUM_FOLDS: 1
  SELECTIVE_BP: 1.
  HARD_MULT: 2
  EMA: True
  #WEIGHTS: 'input/scores_color_train.pkl'
  #INIT_MODEL: 'output/2021_Mar_28_21_49_35_PAMBUH/models/'
  AMP: True
  GPUS: [0,1]
  NUM_WORKERS: 8
  
  SAVE_STEP: .4
  SCALAR_STEP: 1
  TB_STEP: 4
  
  EPOCH_COUNT: 100
  BATCH_SIZE: 64
VALID:
  STEP: 4
  BATCH_SIZE: 32
SSL:
  STEP: 1
  BATCH_SIZE: 64
TEST:
  BATCH_SIZE: 1
  
PARALLEL:
  DDP: True
