INPUTS: input
OUTPUTS: output

DATA:
  TRAIN:
    DATASETS: ['full1024x25', 'backs_20_x25_1024']
    GPU_PRELOAD: False
    PRELOAD: True
    CACHE: False
    MULTIPLY: {'rate':4}
  VALID:
    DATASETS: ['val1024x25']
    PRELOAD: False
  VALID2:
    PRELOAD: False
  TEST:
    DATASETS: []

TRANSFORMERS:
  TRAIN:
    AUG: 'light_scale'
  VALID:
    AUG: 'val'
  VALID2:
    AUG: 'val'
  TEST:
    AUG: 'test'
  CROP: [128, 128]
  RESIZE: [128, 128]

TRAIN:
  DOWNSCALE: 4
  NUM_FOLDS: 4
  SELECTIVE_BP: 1.
  AMP: True
  GPUS: [0,1,2,3]
  NUM_WORKERS: 8
  
  SAVE_STEP: .4
  SCALAR_STEP: 1
  TB_STEP: 10
  
  EPOCH_COUNT: 500
  BATCH_SIZE: 64
VALID:
  STEP: 10
  BATCH_SIZE: 32
TEST:
  BATCH_SIZE: 1
  
PARALLEL:
  DDP: True
