INPUTS: input
OUTPUTS: output

DATA:
  TRAIN:
    DATASETS: ['train1024x05', 'backs_30_1024']
    GPU_PRELOAD: False
    PRELOAD: True
    CACHE: False
    MULTIPLY: {'rate':5}
  VALID:
    DATASETS: ['val1024x05']
    PRELOAD: False
  VALID2:
    PRELOAD: False
  TEST:
    DATASETS: []

TRANSFORMERS:
  TRAIN:
    AUG: 'light_scale'
  VALID:
    AUG: 'val'
  VALID2:
    AUG: 'val'
  TEST:
    AUG: 'test'
  CROP: [256, 256]
  RESIZE: [128, 128]

TRAIN:
  DOWNSCALE: 2
  AMP: True
  GPUS: [0,1,2,3]
  NUM_WORKERS: 8
  
  SAVE_STEP: .2
  SCALAR_STEP: 1
  TB_STEP: 20
  
  EPOCH_COUNT: 500
  BATCH_SIZE: 64
VALID:
  STEP: 20
  BATCH_SIZE: 32
TEST:
  BATCH_SIZE: 1
  
PARALLEL:
  DDP: True
