INPUTS: input
OUTPUTS: output

DATA:
  TRAIN:
    DATASETS: ['train512']
    GPU_PRELOAD: False
    PRELOAD: True
    CACHE: False
  VALID:
    DATASETS: ['val512']
    PRELOAD: False
  TEST:
    DATASETS: []

TRANSFORMERS:
  TRAIN:
    AUG: 'light'
  VALID:
    AUG: 'test'
  TEST:
    AUG: 'test'
  CROP: [256, 256]
  RESIZE: [512, 512]

TRAIN:
  AMP: True
  GPUS: [0,1,2,3]
  NUM_WORKERS: 8
  
  SAVE_STEP: 50
  SCALAR_STEP: 1
  TB_STEP: 3
  
  EPOCH_COUNT: 10
  BATCH_SIZE: 64
VALID:
  BATCH_SIZE: 64
TEST:
  BATCH_SIZE: 1
  
PARALLEL:
  DDP: True
