INPUTS: input
OUTPUTS: output

DATA:
  TRAIN:
    DATASETS: ['train2048x25', 'backs_10_x25_2048', 'backs_10_x25_2048_cortex']
    GPU_PRELOAD: False
    PRELOAD: False
    CACHE: False
    MULTIPLY: {'rate':2}
  VALID:
    DATASETS: ['val2048x25']
    PRELOAD: False
  VALID2:
    DATASETS: ['val2048x25_hard']
    PRELOAD: False
  TEST:
    DATASETS: []

TRANSFORMERS:
  TRAIN:
    AUG: 'light_scale'
  VALID:
    AUG: 'val'
  VALID2:
    AUG: 'val'
  TEST:
    AUG: 'test'
  CROP: [256,256]
  RESIZE: [256,256]
  MEAN:
  - 0.6226
  - 0.4284
  - 0.6705
  STD:
  - 0.1246
  - 0.1719
  - 0.0956

TRAIN:
  LRS: [0.00005, 0.0002, 0.00003, 2]
  DOWNSCALE: 4
  NUM_FOLDS: 1
  SELECTIVE_BP: 1.
  DOUBLE_HARD: True
  INIT_MODEL: 'output/2021_Mar_19_18_47_50_PAMBUH/models/'
  AMP: True
  GPUS: [0,1,2,3]
  NUM_WORKERS: 6
  
  SAVE_STEP: .2
  SCALAR_STEP: 1
  TB_STEP: 5
  
  EPOCH_COUNT: 20
  BATCH_SIZE: 64
VALID:
  STEP: 5
  BATCH_SIZE: 16
VALID2:
  STEP: 5
  BATCH_SIZE: 16
TEST:
  BATCH_SIZE: 1
  
PARALLEL:
  DDP: True
